// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mongo.Services.CupomApi.Data;

#nullable disable

namespace Mongo.Services.CupomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mongo.Services.CupomApi.Entities.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float")
                        .HasColumnName("discount");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int")
                        .HasColumnName("min_amount");

                    b.HasKey("Id");

                    b.ToTable("cupom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "50Off",
                            DiscountAmount = 50.0,
                            MinAmount = 100
                        },
                        new
                        {
                            Id = 2,
                            Code = "20Off",
                            DiscountAmount = 20.0,
                            MinAmount = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
